---
title: "Stat 849 Final"
author: "Lingyun Xiao"
date: '2022-12-20'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Import Dataset

```{r}
Wine <- read.csv(file = 'winequality.csv')
summary(Wine)
```

## Standardize Data

```{r}
Wine <- cbind(scale(Wine[1:11]), Wine[12])
```

## Baseline Model

```{r}
library(car)
lmod1 <- lm(quality ~., data=Wine)
summary(lmod1)
```

### Influential Points

```{r}
plot(lmod1, which = c(1,2,4,5), cook.levels = 1)
```

### Leverages

```{r}
lmod1.hats = hatvalues(lmod1)

plot(lmod1.hats, type="h", ylab="Leverage")

text(lmod1.hats, cex=1)
```

### Outliers

```{r}
library(MASS)
plot(studres(lmod1), type="h", ylab="Studentized residuals")
text(studres(lmod1), cex=1)
abline(h=c(-3,0,3), lty=2)
```

### Remove unusual observations

```{r}
Wine2 <- Wine[-c(2781, 4745, 3307),]

lmod2 <- lm(quality ~., data=Wine2)

summary(lmod2)

plot(lmod2, which = c(1,2,4,5), cook.levels = 1)
```

### Multicollinearity

```{r}
library(corrplot)
corrplot(cor(Wine2))
```

```{r}
vif2 <- vif(lmod2)
vif2
```

```{r}
lmod3 <- lm(quality ~.-density-total.sulfur.dioxide, data=Wine2)
vif3 <- vif(lmod3)
vif3
```

### Best Subset Selection

```{r}
library(leaps)

lmod4 <- regsubsets(quality ~.-citric.acid-density-total.sulfur.dioxide, data=Wine2, nvmax=8, method="exhaustive")

rs <- summary(lmod4)

par(mfrow=c(1,3))

plot(rs$adjr2, xlab="No. of Predictors", ylab="Adjusted R-square")

plot(rs$cp, xlab="No. of Predictors", ylab="Cp Statistic")

plot(rs$bic, xlab="No. of Predictors", ylab="BIC")

which.max(rs$adjr2) 

which.min(rs$cp)

which.min(rs$bic)

rs$which
```

```{r}
lmod5 <- lm(quality ~.-density-total.sulfur.dioxide-citric.acid, data=Wine2)
summary(lmod5)
lmod6 <- lm(quality ~.-density-total.sulfur.dioxide-citric.acid-pH-chlorides, data=Wine2)
summary(lmod6)
```

### LASSO

```{r}
library(glmnet)

X <- model.matrix(quality ~.-density-total.sulfur.dioxide-citric.acid, data=Wine2)[, -1]

Y <- Wine2$quality

cv.out <- cv.glmnet(X, Y, alpha=1) 

par(mfrow=c(1,1))

plot(cv.out)

lambda_opt <- cv.out$lambda.min

predict(cv.out, s = lambda_opt, type = "coefficients")[1:9, ]
```

```{r}
lambda_opt
```

### Output LaTeX tables

```{r}
library(texreg)

texreg(list(lmod1, lmod2, lmod5, lmod6))
```
